### ISSUE TITLE
Decimal values in SVG should use period for decimal symbol

### ISSUE THREAD

**Issue by mgnslndh** [rebornix/DotBadge#3]
DotBadge will output invalid decimal values in the SVG when using a culture that does not have the period as decimal symbol. Decimal values should probably be formatted using the Invariant culture.

**Comment by mgnslndh** [comment]
@rebornix this issue seems to have been fixed by 410836aab8e39d82d5a125ef2a0ac8de6f4507a9 but it has not yet been released.

**Comment by rebornix** [comment]
1.2 was just published. Thanks for your ping ;)
